spring:
  application:
    name: transfer-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:transfer_service_db}
    username: ${POSTGRES_USER:transfer_service}
    password: ${POSTGRES_PASSWORD:transfer_service_password}

  flyway:
    baseline-on-migrate: true
    locations:
      - classpath:db/migration
    enabled: true
