spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:user_service_db}
    username: ${DB_USER:user_service}
    password: ${DB_PASSWORD:user_service_password}

  flyway:
    baseline-on-migrate: true
    locations:
      - classpath:db/migration
    enabled: true
