spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:user_service_db}
    username: ${POSTGRES_USER:user_service}
    password: ${POSTGRES_PASSWORD:user_service_password}

  flyway:
    baseline-on-migrate: true
    locations:
      - classpath:db/migration
    enabled: true
